USE [master]
GO

/****** Object:  Database [registration]    Script Date: 10/09/2020 13:20:57 ******/
CREATE DATABASE [registration]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'registration', FILENAME = N'D:\rdsdbdata\DATA\registration.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'registration_log', FILENAME = N'D:\rdsdbdata\DATA\registration_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [registration].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [registration] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [registration] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [registration] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [registration] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [registration] SET ARITHABORT OFF 
GO

ALTER DATABASE [registration] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [registration] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [registration] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [registration] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [registration] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [registration] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [registration] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [registration] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [registration] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [registration] SET  DISABLE_BROKER 
GO

ALTER DATABASE [registration] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [registration] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [registration] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [registration] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [registration] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [registration] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [registration] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [registration] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [registration] SET  MULTI_USER 
GO

ALTER DATABASE [registration] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [registration] SET DB_CHAINING OFF 
GO

ALTER DATABASE [registration] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [registration] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [registration] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [registration] SET QUERY_STORE = OFF
GO

ALTER DATABASE [registration] SET  READ_WRITE 
GO


